#!/bin/bash
while true ; do 
    for $dev in eth0 eth1; do
        start=`ifconfig $dev| grep "TX packets" | awk '{print $2 }' | cut -d: -f2`
        sleep 1
        end=`ifconfig $dev | grep "TX packets" | awk '{print $2 }' | cut -d: -f2`
        let pktsec=$end-$start
        echo "$dev: $pktsec / second"
    done
done
